# 해당 spring boot 서버를 몇 번 포트 번호로 띄울 것인지에 대한 설정
server:
    port: 9898




# DB 연결 시 mybatis 관련 설정. 현재 아이디어 톤에서는 필요없어 주석 처리
# mabatis:
#     type-aliases-package: com.example.demo.domain
#     configuration:
#         map-underscore-to-camel-case: true #auto change snake_case to camelCase